# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  system.copySystemConfiguration = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4dbbdac2-37a3-4578-a27b-fa43e2d483a3";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd" "autodefrag"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4dbbdac2-37a3-4578-a27b-fa43e2d483a3";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd" "autodefrag"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4dbbdac2-37a3-4578-a27b-fa43e2d483a3";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime" "autodefrag"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C3D6-5EBD";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/526a9c71-bde5-41da-a0bd-77a3d2270d73";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
