#! /usr/bin/env zsh

set -e

autoload colors; colors

printerr() { printf "${fg[yellow]}[for-sys]${fg[blue]}[$(date +%T)]${reset_color} %s\n" "$@" 1>&2; }

typeset -a DIRS
./sys-inputs paths | read -r -A DIRS

for flake in ${DIRS}; do
	printerr "$(print -D -- $flake) :: $argv"
	pushd "$flake"
		xargs -I{} "$@" <<< "$flake"
	popd
done

printerr "done"
