#! /usr/bin/env zsh

typeset -a OVERRIDES
./sys-inputs overrides | read -r -A OVERRIDES

nix why-depends \
	${OVERRIDES} \
	"${XDG_PROJECTS_DIR:-$HOME/projects}/nix/sys/desktop#nixosConfigurations.$(hostname).config.system.build.toplevel" \
	${argv[1,-1]}
